### ISSUE TITLE
DB Entity 생성

### ISSUE THREAD

**Issue by mank1cho** [ChangWoo95/wow#2]
User
Video
Comment

- [x] 위 세가지 항목에 대한 Entity 생성
- [x] serializable 삭제
- [x] 각 Column 에 제약조건들 추가하기.
- [x] builder 생성
- [x] cascade 설정

**Comment by mank1cho** [comment]
@GGoMak Builder를 만들었는데 제대로 한게 맞는지 아리까리 하네요 ^^.. 내일 저도 h2로 확인해볼테니 지수님도 검수 한번 부탁드려요 ^^~

**Comment by GGoMak** [comment]
@mank1cho 말씀하신 Builder오류 수정하였습니다
